SaveWolrdWebApp/SaveWolrdWebApp/Controllers/AuthController.cs
using DocumentFormat.OpenXml.Wordprocessing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaveWolrdWebApp.Controllers
{
    public class AuthController : Controller
    {

        UserServiceReference.UserClient wcfUserService;
        // GET: Auth
        public AuthController()
        {
            wcfUserService = new UserServiceReference.UserClient();

        }

        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult Register()
        {
            return View("Register");
        }

        [HttpGet]
        public ActionResult Login()
        {
           
            return View("Login");
        }

     /*   [HttpPost]
        public ActionResult Login(FormCollection collection)
        {

            var isAuthenticated = false;
            var name = collection["name"];
            var password = collection["password"];

            #region validation
            bool valid = true;
            if (string.IsNullOrWhiteSpace(name))
            {
                valid = false;
                ViewBag.usernameEmpty = "Username is a required field";
            }
            if (string.IsNullOrWhiteSpace(password))
            {
                valid = false;
                ViewBag.passwordEmpty = "Password is a required field";
            }
            //checking if user exists in db with the credentials provided
            if (valid)
            {
                try
                {
                    isAuthenticated = Int32.Parse(wcfUserService.GetUserByName(name));
                }
                catch (Exception)
                {
                    ViewBag.massError = "Internal error has occurred please try again after 5 minutes";
                    return View("Login");
                };

                if (isAuthenticated)
                {
                    HttpCookie authCookie = new HttpCookie("auth");
                    var user = wcfUserService.GetUserByName(name);
                    authCookie.Value = wcfUserService.GetUserIDByName(name).ToString();
                    Response.Cookies.Add(authCookie);
                    Response.Cookies["auth"].Expires.AddDays(3);
                    return Redirect("~/Disaster/Index");//TODO user should be redirected to index page of logged in users
                }
                else
                {
                    ViewBag.username = name;
                    ViewBag.errorNotExisting = "The given credentials do not match";
                    return View("Login");
                }
            }
            else
            {
                ViewBag.username = name;
                return View("Login");
            }

        }

        [HttpPost]
        public void Logout()
        {
            var authCookie = Request.Cookies["auth"];
            if (authCookie != null)
            {
                authCookie.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(authCookie);
                Response.Redirect("~/");
            }
        }
        */
    }
}

SaveWolrdWebApp/SaveWolrdWebApp/Controllers/DisasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SaveWolrdWebApp.Controllers
{
    public class DisasterController : Controller
    {
        DisasterServiceReference.DisasterServiceClient disasterService = new DisasterServiceReference.DisasterServiceClient();
        BankAccountServiceReference.BankAccountB userBankId = new BankAccountServiceReference.BankAccountB();
        BankAccountServiceReference.BankAccountB disasterBankId = new BankAccountServiceReference.BankAccountB();
        // GET: Disaster
        public ActionResult Index()
        {
            DisasterServiceReference.DisasterServiceClient disClient = new DisasterServiceReference.DisasterServiceClient();

            return View(disClient.GetAllDisasters());
        }

        public ActionResult Details(DisasterController disaster)
        {
            return View();
        }

        public ActionResult Create(DisasterServiceReference.DisasterB disaster)
        {
            DisasterServiceReference.DisasterServiceClient disClient = new DisasterServiceReference.DisasterServiceClient();
            disClient.CreateDisaster();

            return View();
        }
        public ActionResult Donate(int disasterAccId, decimal amount)
        {
            BankAccountServiceReference.BankAccountServiceClient bank = new BankAccountServiceReference.BankAccountServiceClient();
            bank.donateToSpecificDisaster(amount, 2, disasterAccId);
            return View();
        }

        public ActionResult Delete(DisasterServiceReference.DisasterB disaster)
        {
            DisasterServiceReference.DisasterServiceClient disClient = new DisasterServiceReference.DisasterServiceClient();
            
            disClient.DeleteDisaster(disaster.DisasterId);
                
              
            
            return View();
        }

        public ActionResult Edit( )
        {
            BankAccountServiceReference.BankAccountServiceClient bank = new BankAccountServiceReference.BankAccountServiceClient();
            bank.donateToSpecificDisaster(2, 2, 5);
            return View();
        }
    }

}

SaveWolrdWebApp/SaveWolrdWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaveWolrdWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult User()
        {
            return View();
        }
    }
}

SaveWolrdWebApp/SaveWolrdWebApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaveWolrdWebApp.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            ProductServiceReference.ProductServiceClient obj = new ProductServiceReference.ProductServiceClient();

            return View(obj.GetAllProduct());
        }

        public ActionResult Details(ProductController product)
        {
            return View();
        }

        public ActionResult Create(ProductController product)
        {

            return View();
        }

        public ActionResult Delete(ProductController product)
        {

            return View();
        }

        public ActionResult Edit(ProductController product)
        {

            return View();
        }

    }
}

SaveWolrdWebApp/SaveWolrdWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaveWolrdWebApp.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            UserServiceReference.UserClient obj = new UserServiceReference.UserClient();
            UserServiceReference.UserB user = new UserServiceReference.UserB(); 

            return View(obj.GetAllUsers());
        }

        public ActionResult Details(UserController user)
        {
            return View();
        }

        public ActionResult Create(UserController user)
        {

            try
            {
                using (UserServiceReference.UserClient wcf = new UserServiceReference.UserClient())
                {
                   
                }

                return RedirectToAction("Index");
            }
            catch
            { 
            return View();
            }
        }

        public ActionResult Delete(UserController user)
        {
            using (UserServiceReference.UserClient wcf = new UserServiceReference.UserClient())
            {
             //   wcf.DeleteUser(user); 
            }
            
            return View();
        }

        public ActionResult Edit(UserController user)
        {
            using (UserServiceReference.UserClient client = new UserServiceReference.UserClient())
            {
               
            }
            return View();
        }
    }
}

SaveWolrdWebApp/SaveWolrdWebApp/Views/Disaster/Create.cshtml
@model SaveWolrdWebApp.DisasterServiceReference.DisasterB

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DisasterB</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisasterBankAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisasterBankAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisasterBankAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisasterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisasterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisasterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Victims, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Victims, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Victims, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Disaster/Delete.cshtml
@model SaveWolrdWebApp.DisasterServiceReference.DisasterB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DisasterB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId) 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisasterBankAccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisasterBankAccountId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisasterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisasterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Victims)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Victims)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Disaster/Details.cshtml
@model SaveWolrdWebApp.DisasterServiceReference.DisasterB

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DisasterB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisasterBankAccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisasterBankAccountId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisasterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisasterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Victims)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Victims)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Disaster/Donate.cshtml
@{
    ViewBag.Title = "Donate";
}

<h2>Donate</h2>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Disaster/Edit.cshtml
@model SaveWolrdWebApp.DisasterServiceReference.DisasterB

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DisasterB</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-form-label col-form-label-lg" for="inputLarge">Large input</label>
        <input class="col-md-offset-2 col-md-10" type="text" placeholder=".form-control-lg" id="inputLarge">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisasterBankAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DisasterBankAccountId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DisasterBankAccountId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisasterId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DisasterId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DisasterId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Victims, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Victims, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Victims, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Disaster/Index.cshtml
@model IEnumerable<SaveWolrdWebApp.DisasterServiceReference.DisasterB>

@{
    ViewBag.Title = "Index";
}

<h2>Disasters</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisasterBankAccountId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisasterId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Victims)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisasterBankAccountId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisasterId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priority)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Region)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Victims)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { item.DisasterId }, new { @class = "btn btn-info col-md-5" })
            @Html.ActionLink("Donate", "Donate", new {item.DisasterBankAccountId}, new { @class = "btn btn-info col-md-5" })
        </td>
    </tr>
}

</table>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Let's change the world.</p>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    If any problems with donatation, please contact the support.<br />
    Aalborg, Denmark - Sofiendalsvej 60<br />
    <abbr title="Phone">P:</abbr>
    60509933
</address>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Save The World for Admins</h1>
    <p class="lead">Everything at one place.</p>
    <p><a href="~/Auth/" class="btn btn-primary btn-lg">Login &raquo;</a></p>
</div>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Product/Delete.cshtml
@model SaveWolrdWebApp.ProductServiceReference.ProductB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SaveWolrdWebApp/SaveWolrdWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.Cookies["auth"] != null)
                    {
                        <li>@Html.ActionLink("Catalog", "Index", "Product")</li>
                        if (ViewBag.user != null && ViewBag.user.IsAdmin)
                        {
                            <li>@Html.ActionLink("Create product", "Create", "Product")</li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.Cookies["auth"] != null)
                    {
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@(ViewBag.user.Name ?? "") - @(ViewBag.user.Coins ?? "") Coins</a>
                            <div class="dropdown-menu navbar-inverse custom-dropdown">
                                <div class="container">
                                    <a class="dropdown-item" href="@Url.Action("Edit", "User", new { userId = ViewBag.user.Id})">My Profile</a>
                                    <hr style="border: 0.5px solid lightslategrey;" />
                                    <a class="dropdown-item button" onclick="jQuery('#logout-form').submit()">Log out</a>
                                    <form action=@Url.Action("Logout", "Auth") method="post" id="logout-form"></form>
                                </div>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Index", "Auth")</li>
                        <li>@Html.ActionLink("Register", "Register", "Auth")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p id="copyright">&copy; @DateTime.Now.Year - SaveTheWorld</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>